import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import { DarkModeContextProvider } from '@/contexts/DarkModeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: ReactNode }) {
  return (
    <html lang="pt-BR" className={`${inter.className} dark`}>
      <body className='bg-slate-50 dark:bg-slate-950'>
        <DarkModeContextProvider>
          {children}
        </DarkModeContextProvider>
      </body>
    </html>
  )
}
