import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import { DarkModeContextProvider } from '../contexts/DarkModeContext'
import { dir } from 'i18next'
import { languages } from '../i18n/settings'

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

interface Props {
  children: ReactNode
  params: {
    lng: string
  }
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {
    lng
  }
}: Props) {
  return (
    <html lang={lng} dir={dir(lng)} className={`${inter.className} dark`}>
      <body className='bg-slate-50 dark:bg-slate-950'>
        <DarkModeContextProvider>
          {children}
        </DarkModeContextProvider>
      </body>
    </html>
  )
}
